SET VER ON
SET FEED ON
COLUMN MAPA NEW_VAL MAPA
SELECT SUBSTR('&MAP',1,17) MAPA FROM DUAL
/

SELECT SQL_ID,
       (SUM(B.ELAPSED_TIME_DELTA)) / 1000000 AS ELAPSED_TIME,
       SUM(B.EXECUTIONS_DELTA) AS EXECUTIONS,
       SUM(B.BUFFER_GETS_DELTA) AS BUFFER_GETS,
       (SUM(B.CPU_TIME_DELTA)) / 1000000 AS CPU_TIME,
       SUM(B.DISK_READS_DELTA) AS DISK_READS,
       SUM(B.FETCHES_DELTA) AS FETCHES,
       SUM(B.ROWS_PROCESSED_DELTA) AS ROWS_PROCESSED
  FROM DBA_HIST_SNAPSHOT A, DBA_HIST_SQLSTAT B
 WHERE A.SNAP_ID BETWEEN
       (SELECT MIN(SNAP_ID)
          FROM DBA_HIST_SNAPSHOT
         WHERE BEGIN_INTERVAL_TIME >=
               TO_DATE('&DATA_INICIAL', 'DD/MM/YYYY HH24:MI:SS')) AND
       (SELECT MAX(SNAP_ID)
          FROM DBA_HIST_SNAPSHOT
         WHERE BEGIN_INTERVAL_TIME <=
               TO_DATE('&DATA_FINAL', 'DD/MM/YYYY HH24:MI:SS'))
   AND A.SNAP_ID = B.SNAP_ID
   AND A.DBID = B.DBID
   AND A.INSTANCE_NUMBER = B.INSTANCE_NUMBER
   AND B.PLAN_HASH_VALUE <> 0
   AND UPPER(B.MODULE) LIKE '%&&MAPA%'
 GROUP BY SQL_ID
 ORDER BY 2 DESC
 /

 SET VER ON


 