COL STATUS FOR a10
SELECT INPUT_TYPE  ARQUIVO
,OUTPUT_DEVICE_TYPE 
    ,      STATUS
    ,      TO_CHAR(START_TIME,'mm/dd/yy hh24:mi') INICIO
    ,      TO_CHAR(END_TIME,'mm/dd/yy hh24:mi')   TERMINO
    ,      ROUND((ELAPSED_SECONDS/3600),2)        DURACAO  
    ,      INPUT_BYTES/1024/1024/1024             "INPUT_BYTES EM GB"
    FROM   V$RMAN_BACKUP_JOB_DETAILS
    WHERE START_TIME > SYSDATE -7
    ORDER BY 1,3
/
