select DB_KEY
     , DB_NAME
     , CONTROLFILE_TYPE
     , STATUS, RESETLOGS_TIME
     , COMPLETION_TIME
     , AUTOBACKUP_DATE
     , AUTOBACKUP_SEQUENCE 
from RC_BACKUP_CONTROLFILE where DB_NAME = &pdbname;

--PROD=90542
select DB_KEY
     , MODIFICATION_TIME
     , COMPLETION_TIME
     , STATUS
     , BYTES
from RC_BACKUP_SPFILE where db_key=&pdbid;


select DB_NAME
     , THREAD#
     , SEQUENCE#
     , to_char(FIRST_TIME, 'dd/mm/yyyy hh24:mi:ss') FIRST_TIME
     , COMPRESSION_RATIO 
  from RC_BACKUP_ARCHIVELOG_DETAILS order by SEQUENCE#;

select * from rman.RC_UNUSABLE_BACKUPFILE_DETAILS;

select DB_NAME
     , FILETYPE
     , STATUS
     , FILESIZE
     , DEVICE_TYPE
     , FILENAME
     , MEDIA
     , MEDIA_POOL 
  from RC_UNUSABLE_BACKUPFILE_DETAILS where DB_NAME like &pdbname;


SELECT *
  FROM RC_BACKUP_SET
 WHERE DB_KEY=1
 order by START_TIME;
 

SELECT A.DB_NAME
     , A.STATUS
     , A.BS_KEY
     , A.SET_COUNT AS BACKUPSET
     , A.BACKUP_TYPE
     , A.INCREMENTAL_LEVEL
     , A.START_TIME
     , A.COMPLETION_TIME
     , A.CONTROLFILE_INCLUDED
     , A.NUM_COPIES
     , A.SESSION_KEY
     , A.SESSION_RECID
     , A.SESSION_STAMP
  FROM RC_BACKUP_SET_DETAILS A 
 WHERE DB_NAME LIKE 'ARARASH'
 order by A.START_TIME;


SELECT A.DB_NAME
     , A.STATUS
     , A.BS_KEY
     , A.SET_COUNT AS BACKUPSET
     , A.BACKUP_TYPE
     , A.INCREMENTAL_LEVEL
     , A.START_TIME
     , A.COMPLETION_TIME
     , A.CONTROLFILE_INCLUDED
     , A.NUM_COPIES
     , A.SESSION_KEY
     , A.SESSION_RECID
     , A.SESSION_STAMP
  FROM RC_BACKUP_SET_DETAILS A 
 WHERE A.SET_COUNT IN (170, 173, 210, 213, 256, 259, 329, 331, 369)
 ORDER BY A.START_TIME;



COL HANDLE FORM A30
COL TAG FORM A20
COL COMMENTS FORM A20
COL MEDIA FORM A10

SELECT A.DB_ID
     , B.DB_NAME
     , A.HANDLE
     , A.TAG
     , A.BACKUP_TYPE
     , A.MEDIA
     , A.START_TIME
     , A.COMPLETION_TIME
     , A.ELAPSED_SECONDS
     , A.STATUS  
     , B.INCREMENTAL_LEVEL AS ILEVEL
     , B.COMPRESSED
     , B.MEDIA_POOL
  FROM RC_BACKUP_PIECE A
     , RC_BACKUP_PIECE_DETAILS B
 WHERE UPPER(A.HANDLE) LIKE '%FULL_ONLINE_DB_PROD_S7IU%'
   AND A.DB_KEY = B.DB_KEY
   AND A.DB_ID = B.DB_ID
   AND A.BP_KEY = B.BP_KEY
   AND B.DB_NAME LIKE &pdbname;



COL HANDLE FORM A30
COL TAG FORM A20
COL COMMENTS FORM A20
COL MEDIA FORM A10

SELECT A.DB_ID
     , B.DB_NAME
     , A.HANDLE
     , A.TAG
     , A.BACKUP_TYPE
     , A.MEDIA
     , A.START_TIME
     , A.COMPLETION_TIME
     , A.ELAPSED_SECONDS
     , A.STATUS  
     , B.INCREMENTAL_LEVEL AS ILEVEL
     , B.COMPRESSED
     , B.MEDIA_POOL
  FROM RC_BACKUP_PIECE A
     , RC_BACKUP_PIECE_DETAILS B
 WHERE UPPER(A.TAG) LIKE '%TAG20071019T002149%'
   AND UPPER(A.HANDLE) LIKE '%FULL_ONLINE_ARC_PROD_19IUR%'
   AND A.DB_KEY = B.DB_KEY
   AND A.DB_ID = B.DB_ID
   AND A.BP_KEY = B.BP_KEY
   AND B.DB_NAME LIKE &pdbname;


COL HANDLE FORM A32
COL TAG FORM A20
COL COMMENTS FORM A20
COL MEDIA FORM A18
SET PAGES 1200
SET LIN 200

SELECT A.DB_ID
     , B.DB_NAME
     , A.HANDLE
     , A.TAG
     , A.BACKUP_TYPE
     , A.MEDIA
     , A.START_TIME
     , A.COMPLETION_TIME
     , A.ELAPSED_SECONDS ELA_SECONDS
     , A.STATUS  
     , B.INCREMENTAL_LEVEL AS ILEVEL
     , B.COMPRESSED
     , B.MEDIA_POOL
  FROM RC_BACKUP_PIECE A
     , RC_BACKUP_PIECE_DETAILS B
 WHERE TO_CHAR(A.START_TIME, 'DD-MON-YY') = '10-OCT-07'
   AND A.DB_KEY = B.DB_KEY
   AND A.DB_ID = B.DB_ID
   AND A.BP_KEY = B.BP_KEY
   AND B.DB_NAME LIKE &pdbname
 ORDER BY A.START_TIME, A.TAG;
 
 
 
 
 
 
 
 OBJECT_NAME
 ------------------------------
 RCVER
 RCVER_VERSION_UNIQUE
 RC_ARCHIVED_LOG
 RC_BACKUP_ARCHIVELOG_DETAILS
 RC_BACKUP_ARCHIVELOG_SUMMARY
 RC_BACKUP_CONTROLFILE
 RC_BACKUP_CONTROLFILE_DETAILS
 RC_BACKUP_CONTROLFILE_SUMMARY
 RC_BACKUP_COPY_DETAILS
 RC_BACKUP_COPY_SUMMARY
 RC_BACKUP_CORRUPTION
 RC_BACKUP_DATAFILE
 RC_BACKUP_DATAFILE_DETAILS
 RC_BACKUP_DATAFILE_SUMMARY
 RC_BACKUP_FILES
 RC_BACKUP_PIECE
 RC_BACKUP_PIECE_DETAILS
 RC_BACKUP_REDOLOG
 RC_BACKUP_SET
 RC_BACKUP_SET_DETAILS
 RC_BACKUP_SET_SUMMARY
 RC_BACKUP_SPFILE
 RC_BACKUP_SPFILE_DETAILS
 RC_BACKUP_SPFILE_SUMMARY
 RC_CHECKPOINT
 RC_CONTROLFILE_COPY
 RC_COPY_CORRUPTION
 RC_DATABASE
 RC_DATABASE_BLOCK_CORRUPTION
 RC_DATABASE_INCARNATION
 RC_DATAFILE
 RC_DATAFILE_COPY
 RC_LBRECSETIMPL_T
 RC_LBRECSETIMPL_T
 RC_LBRECSET_T
 RC_LBREC_T
 RC_LISTBACKUPPIPE
 RC_LOG_HISTORY
 RC_OFFLINE_RANGE
 RC_PROXY_ARCHIVEDLOG
 RC_PROXY_ARCHIVELOG_DETAILS
 RC_PROXY_ARCHIVELOG_SUMMARY
 RC_PROXY_CONTROLFILE
 RC_PROXY_COPY_DETAILS
 RC_PROXY_COPY_SUMMARY
 RC_PROXY_DATAFILE
 RC_REDO_LOG
 RC_REDO_THREAD
 RC_RESYNC
 RC_RMAN_BACKUP_JOB_DETAILS
 RC_RMAN_BACKUP_SUBJOB_DETAILS
 RC_RMAN_BACKUP_TYPE
 RC_RMAN_CONFIGURATION
 RC_RMAN_OUTPUT
 RC_RMAN_STATUS
 RC_STORED_SCRIPT
 RC_STORED_SCRIPT_LINE
 RC_TABLESPACE
 RC_TEMPFILE
 RC_UNUSABLE_BACKUPFILE_DETAILS
 
 60 rows selected.




13:17:02 23-OCT-08 [HOMOLOGBKP] [dbrmanh] >select DBID, NAME, DB_KEY from RC_DATABASE;

      DBID NAME         DB_KEY
---------- -------- ----------
1038753341 WEBH           2193
1347284794 DWH2           2848
  77159297 ARARASH           1
1059823650 DBTEST        13213
3220450743 WEBD          17839
1302694590 ARARASD       18624
3183327873 DWD           18184

7 rows selected.



SELECT DB_NAME
     , DB_KEY 
     , NUM_BACKUPSETS
     , OLDEST_BACKUP_TIME
     , NEWEST_BACKUP_TIME
     , OUTPUT_BYTES
     , ORIGINAL_INPUT_BYTES 
     , ORIGINAL_INPRATE_BYTES 
     , OUTPUT_RATE_BYTES 
     , COMPRESSION_RATIO 
     , SUBSTR(ORIGINAL_INPUT_BYTES_DISPLAY,1,15)   ORIGINAL_INPUT_BYTES_DISPLAY
     , SUBSTR(OUTPUT_BYTES_DISPLAY,1,15)           OUTPUT_BYTES_DISPLAY
     , SUBSTR(ORIGINAL_INPRATE_BYTES_DISPLAY,1,15) ORIGINAL_INPRATE_BYTES_DISPLAY
     , SUBSTR(OUTPUT_RATE_BYTES_DISPLAY,1,15)      OUTPUT_RATE_BYTES_DISPLAY
  FROM RC_BACKUP_SET_SUMMARY 
 WHERE DB_NAME = 'ARARASH' 
 ORDER BY OLDEST_BACKUP_TIME;




 SELECT RECID
      , STAMP
      , SET_STAMP
      , SET_COUNT
      , BACKUP_TYPE
      , CONTROLFILE_INCLUDED
      , INCREMENTAL_LEVEL 
      , PIECES
      , START_TIME 
      , COMPLETION_TIME
      , ELAPSED_SECONDS
      , BLOCK_SIZE     
      , INPUT_FILE_SCAN_ONLY  
      , KEEP 
      , KEEP_UNTIL   
      , KEEP_OPTIONS 
   FROM V$BACKUP_SET
  WHERE SET_COUNT IN (170, 173, 210, 213, 256, 259, 329, 331, 369)
  ORDER BY START_TIME;