SPO coe_xfr_sql_profile_bqmu54c7r5czr_820084277.log;
SET ECHO ON TERM ON LIN 2000 TRIMS ON NUMF 99999999999999999999;
REM
REM $Header: 215187.1 coe_xfr_sql_profile_bqmu54c7r5czr_820084277.sql 11.4.1.4 2017/09/29 csierra $
REM
REM Copyright (c) 2000-2010, Oracle Corporation. All rights reserved.
REM
REM AUTHOR
REM   carlos.sierra@oracle.com
REM
REM SCRIPT
REM   coe_xfr_sql_profile_bqmu54c7r5czr_820084277.sql
REM
REM DESCRIPTION
REM   This script is generated by coe_xfr_sql_profile.sql
REM   It contains the SQL*Plus commands to create a custom
REM   SQL Profile for SQL_ID bqmu54c7r5czr based on plan hash
REM   value 820084277.
REM   The custom SQL Profile to be created by this script
REM   will affect plans for SQL commands with signature
REM   matching the one for SQL Text below.
REM   Review SQL Text and adjust accordingly.
REM
REM PARAMETERS
REM   None.
REM
REM EXAMPLE
REM   SQL> START coe_xfr_sql_profile_bqmu54c7r5czr_820084277.sql;
REM
REM NOTES
REM   1. Should be run as SYSTEM or SYSDBA.
REM   2. User must have CREATE ANY SQL PROFILE privilege.
REM   3. SOURCE and TARGET systems can be the same or similar.
REM   4. To drop this custom SQL Profile after it has been created:
REM      EXEC DBMS_SQLTUNE.DROP_SQL_PROFILE('coe_bqmu54c7r5czr_820084277');
REM   5. Be aware that using DBMS_SQLTUNE requires a license
REM      for the Oracle Tuning Pack.
REM
WHENEVER SQLERROR EXIT SQL.SQLCODE;
REM
VAR signature NUMBER;
REM
DECLARE
sql_txt CLOB;
h       SYS.SQLPROF_ATTR;
BEGIN
sql_txt := q'[
SELECT SUM(NVL(C.VL_PAGO_PARCELA, 0)) FROM F_REMESSA_PRODUTO_AFILIADO_FE C WHERE C.SK_DT_PAGAMENTO_REEMBOLSO BETWEEN :B2 AND :B1 AND EXISTS (SELECT 'x' FROM F_CONSUMO_TRANSACOES TRS WHERE TRS.NU_ANO_EMISSAO_REMESSA = C.NU_ANO_REMESSA AND TRS.NU_LOCAL_PREPARACAO_REMESSA = C.CD_LOCAL_PREPARACAO_REMESSA AND TRS.NU_TIPO_NUMERACAO_REMESSA = C.TP_REMESSA AND TRS.NU_NUMERO_REMESSA = C.NU_REMESSA AND TRS.NU_PARCELA = C.NU_PARCELA AND TRS.SK_DT_PAGAMENTO_REEMBOLSO = C.SK_DT_PAGAMENTO_REEMBOLSO AND TRS.SK_DT_EFETIVACAO_LANCAMENTO <> -1)
]';
h := SYS.SQLPROF_ATTR(
q'[BEGIN_OUTLINE_DATA]',
q'[IGNORE_OPTIM_EMBEDDED_HINTS]',
q'[OPTIMIZER_FEATURES_ENABLE('11.2.0.4')]',
q'[DB_VERSION('11.2.0.4')]',
q'[OPT_PARAM('_push_join_predicate' 'false')]',
q'[OPT_PARAM('_push_join_union_view' 'false')]',
q'[OPT_PARAM('_optim_peek_user_binds' 'false')]',
q'[OPT_PARAM('_optimizer_cost_based_transformation' 'off')]',
q'[OPT_PARAM('_push_join_union_view2' 'false')]',
q'[OPT_PARAM('_optimizer_push_pred_cost_based' 'false')]',
q'[ALL_ROWS]',
q'[OUTLINE_LEAF(@"SEL$5DA710D3")]',
q'[UNNEST(@"SEL$2")]',
q'[OUTLINE(@"SEL$1")]',
q'[OUTLINE(@"SEL$2")]',
q'[INDEX_RS_ASC(@"SEL$5DA710D3" "C"@"SEL$1" ("F_REMESSA_PRODUTO_AFILIADO_FE"."SK_DT_PAGAMENTO_REEMBOLSO"))]',
q'[BITMAP_TREE(@"SEL$5DA710D3" "TRS"@"SEL$2" AND(("F_CONSUMO_TRANSACOES"."SK_DT_PAGAMENTO_REEMBOLSO") MINUS_NULL(("F_CONSUMO_TRANSACOES"."SK_DT_EFETIVACAO_LANCAMENTO")) MINUS(("F_CONSUMO_TRANSACOES"."SK_DT_EFETIVACAO_LANCAMENTO"))))]',
q'[LEADING(@"SEL$5DA710D3" "C"@"SEL$1" "TRS"@"SEL$2")]',
q'[USE_HASH(@"SEL$5DA710D3" "TRS"@"SEL$2")]',
q'[PQ_DISTRIBUTE(@"SEL$5DA710D3" "TRS"@"SEL$2" HASH HASH)]',
q'[END_OUTLINE_DATA]');
:signature := DBMS_SQLTUNE.SQLTEXT_TO_SIGNATURE(sql_txt);
DBMS_SQLTUNE.IMPORT_SQL_PROFILE (
sql_text    => sql_txt,
profile     => h,
name        => 'coe_bqmu54c7r5czr_820084277',
description => 'coe bqmu54c7r5czr 820084277 '||:signature||'',
category    => 'DEFAULT',
validate    => TRUE,
replace     => TRUE,
force_match => FALSE /* TRUE:FORCE (match even when different literals in SQL). FALSE:EXACT (similar to CURSOR_SHARING) */ );
END;
/
WHENEVER SQLERROR CONTINUE
SET ECHO OFF;
PRINT signature
PRO
PRO ... manual custom SQL Profile has been created
PRO
SET TERM ON ECHO OFF LIN 80 TRIMS OFF NUMF "";
SPO OFF;
PRO
PRO COE_XFR_SQL_PROFILE_bqmu54c7r5czr_820084277 completed
