
set lines 250 pages 5000
/*
SELECT 'CREATE TABLE %OWNER.'||OBJECT_NAME||' AS SELECT * FROM '||OBJECT_NAME||' WHERE DBID = %DBID;' 
	FROM DBA_OBJECTS 
WHERE OBJECT_NAME  LIKE 'DBA_HIST_%' AND OWNER = 'SYS' 
ORDER BY OBJECT_NAME
/
*/


CREATE TABLE &&OWNER..DBA_HIST_ACTIVE_SESS_HISTORY AS SELECT * FROM DBA_HIST_ACTIVE_SESS_HISTORY WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_ASH_SNAPSHOT AS SELECT * FROM DBA_HIST_ASH_SNAPSHOT WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_BASELINE AS SELECT * FROM DBA_HIST_BASELINE WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_BASELINE_DETAILS AS SELECT * FROM DBA_HIST_BASELINE_DETAILS WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_BASELINE_METADATA AS SELECT * FROM DBA_HIST_BASELINE_METADATA WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_BASELINE_TEMPLATE AS SELECT * FROM DBA_HIST_BASELINE_TEMPLATE WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_BG_EVENT_SUMMARY AS SELECT * FROM DBA_HIST_BG_EVENT_SUMMARY WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_BUFFERED_QUEUES AS SELECT * FROM DBA_HIST_BUFFERED_QUEUES WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_BUFFERED_SUBSCRIBERS AS SELECT * FROM DBA_HIST_BUFFERED_SUBSCRIBERS WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_BUFFER_POOL_STAT AS SELECT * FROM DBA_HIST_BUFFER_POOL_STAT WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_CLUSTER_INTERCON AS SELECT * FROM DBA_HIST_CLUSTER_INTERCON WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_COLORED_SQL AS SELECT * FROM DBA_HIST_COLORED_SQL WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_COMP_IOSTAT AS SELECT * FROM DBA_HIST_COMP_IOSTAT WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_CR_BLOCK_SERVER AS SELECT * FROM DBA_HIST_CR_BLOCK_SERVER WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_CURRENT_BLOCK_SERVER AS SELECT * FROM DBA_HIST_CURRENT_BLOCK_SERVER WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_DATABASE_INSTANCE AS SELECT * FROM DBA_HIST_DATABASE_INSTANCE WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_DATAFILE AS SELECT * FROM DBA_HIST_DATAFILE WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_DB_CACHE_ADVICE AS SELECT * FROM DBA_HIST_DB_CACHE_ADVICE WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_DISPATCHER AS SELECT * FROM DBA_HIST_DISPATCHER WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_DLM_MISC AS SELECT * FROM DBA_HIST_DLM_MISC WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_DYN_REMASTER_STATS AS SELECT * FROM DBA_HIST_DYN_REMASTER_STATS WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_ENQUEUE_STAT AS SELECT * FROM DBA_HIST_ENQUEUE_STAT WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_EVENT_HISTOGRAM AS SELECT * FROM DBA_HIST_EVENT_HISTOGRAM WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_EVENT_NAME AS SELECT * FROM DBA_HIST_EVENT_NAME WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_FILEMETRIC_HISTORY AS SELECT * FROM DBA_HIST_FILEMETRIC_HISTORY WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_FILESTATXS AS SELECT * FROM DBA_HIST_FILESTATXS WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_IC_CLIENT_STATS AS SELECT * FROM DBA_HIST_IC_CLIENT_STATS WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_IC_DEVICE_STATS AS SELECT * FROM DBA_HIST_IC_DEVICE_STATS WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_INSTANCE_RECOVERY AS SELECT * FROM DBA_HIST_INSTANCE_RECOVERY WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_INST_CACHE_TRANSFER AS SELECT * FROM DBA_HIST_INST_CACHE_TRANSFER WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_INTERCONNECT_PINGS AS SELECT * FROM DBA_HIST_INTERCONNECT_PINGS WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_IOSTAT_DETAIL AS SELECT * FROM DBA_HIST_IOSTAT_DETAIL WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_IOSTAT_FILETYPE AS SELECT * FROM DBA_HIST_IOSTAT_FILETYPE WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_IOSTAT_FILETYPE_NAME AS SELECT * FROM DBA_HIST_IOSTAT_FILETYPE_NAME WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_IOSTAT_FUNCTION AS SELECT * FROM DBA_HIST_IOSTAT_FUNCTION WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_IOSTAT_FUNCTION_NAME AS SELECT * FROM DBA_HIST_IOSTAT_FUNCTION_NAME WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_JAVA_POOL_ADVICE AS SELECT * FROM DBA_HIST_JAVA_POOL_ADVICE WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_LATCH AS SELECT * FROM DBA_HIST_LATCH WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_LATCH_CHILDREN AS SELECT * FROM DBA_HIST_LATCH_CHILDREN WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_LATCH_MISSES_SUMMARY AS SELECT * FROM DBA_HIST_LATCH_MISSES_SUMMARY WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_LATCH_NAME AS SELECT * FROM DBA_HIST_LATCH_NAME WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_LATCH_PARENT AS SELECT * FROM DBA_HIST_LATCH_PARENT WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_LIBRARYCACHE AS SELECT * FROM DBA_HIST_LIBRARYCACHE WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_LOG AS SELECT * FROM DBA_HIST_LOG WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_MEM_DYNAMIC_COMP AS SELECT * FROM DBA_HIST_MEM_DYNAMIC_COMP WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_MEMORY_RESIZE_OPS AS SELECT * FROM DBA_HIST_MEMORY_RESIZE_OPS WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_MEMORY_TARGET_ADVICE AS SELECT * FROM DBA_HIST_MEMORY_TARGET_ADVICE WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_METRIC_NAME AS SELECT * FROM DBA_HIST_METRIC_NAME WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_MTTR_TARGET_ADVICE AS SELECT * FROM DBA_HIST_MTTR_TARGET_ADVICE WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_MUTEX_SLEEP AS SELECT * FROM DBA_HIST_MUTEX_SLEEP WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_OPTIMIZER_ENV AS SELECT * FROM DBA_HIST_OPTIMIZER_ENV WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_OSSTAT AS SELECT * FROM DBA_HIST_OSSTAT WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_OSSTAT_NAME AS SELECT * FROM DBA_HIST_OSSTAT_NAME WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_PARAMETER AS SELECT * FROM DBA_HIST_PARAMETER WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_PARAMETER_NAME AS SELECT * FROM DBA_HIST_PARAMETER_NAME WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_PERSISTENT_QUEUES AS SELECT * FROM DBA_HIST_PERSISTENT_QUEUES WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_PERSISTENT_SUBS AS SELECT * FROM DBA_HIST_PERSISTENT_SUBS WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_PGASTAT AS SELECT * FROM DBA_HIST_PGASTAT WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_PGA_TARGET_ADVICE AS SELECT * FROM DBA_HIST_PGA_TARGET_ADVICE WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_PLAN_OPERATION_NAME AS SELECT * FROM DBA_HIST_PLAN_OPERATION_NAME WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_PLAN_OPTION_NAME AS SELECT * FROM DBA_HIST_PLAN_OPTION_NAME WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_PROCESS_MEM_SUMMARY AS SELECT * FROM DBA_HIST_PROCESS_MEM_SUMMARY WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_RESOURCE_LIMIT AS SELECT * FROM DBA_HIST_RESOURCE_LIMIT WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_ROWCACHE_SUMMARY AS SELECT * FROM DBA_HIST_ROWCACHE_SUMMARY WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_RSRC_CONSUMER_GROUP AS SELECT * FROM DBA_HIST_RSRC_CONSUMER_GROUP WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_RSRC_PLAN AS SELECT * FROM DBA_HIST_RSRC_PLAN WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_RULE_SET AS SELECT * FROM DBA_HIST_RULE_SET WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_SEG_STAT AS SELECT * FROM DBA_HIST_SEG_STAT WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_SEG_STAT_OBJ AS SELECT * FROM DBA_HIST_SEG_STAT_OBJ WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_SERVICE_NAME AS SELECT * FROM DBA_HIST_SERVICE_NAME WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_SERVICE_STAT AS SELECT * FROM DBA_HIST_SERVICE_STAT WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_SERVICE_WAIT_CLASS AS SELECT * FROM DBA_HIST_SERVICE_WAIT_CLASS WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_SESSMETRIC_HISTORY AS SELECT * FROM DBA_HIST_SESSMETRIC_HISTORY WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_SESS_TIME_STATS AS SELECT * FROM DBA_HIST_SESS_TIME_STATS WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_SGA AS SELECT * FROM DBA_HIST_SGA WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_SGASTAT AS SELECT * FROM DBA_HIST_SGASTAT WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_SGA_TARGET_ADVICE AS SELECT * FROM DBA_HIST_SGA_TARGET_ADVICE WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_SHARED_POOL_ADVICE AS SELECT * FROM DBA_HIST_SHARED_POOL_ADVICE WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_SHARED_SERVER_SUMMARY AS SELECT * FROM DBA_HIST_SHARED_SERVER_SUMMARY WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_SNAP_ERROR AS SELECT * FROM DBA_HIST_SNAP_ERROR WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_SNAPSHOT AS SELECT * FROM DBA_HIST_SNAPSHOT WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_SQLBIND AS SELECT * FROM DBA_HIST_SQLBIND WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_SQL_BIND_METADATA AS SELECT * FROM DBA_HIST_SQL_BIND_METADATA WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_SQLCOMMAND_NAME AS SELECT * FROM DBA_HIST_SQLCOMMAND_NAME WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_SQL_PLAN AS SELECT * FROM DBA_HIST_SQL_PLAN WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_SQLSTAT AS SELECT * FROM DBA_HIST_SQLSTAT WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_SQL_SUMMARY AS SELECT * FROM DBA_HIST_SQL_SUMMARY WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_SQLTEXT AS SELECT * FROM DBA_HIST_SQLTEXT WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_SQL_WORKAREA_HSTGRM AS SELECT * FROM DBA_HIST_SQL_WORKAREA_HSTGRM WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_STAT_NAME AS SELECT * FROM DBA_HIST_STAT_NAME WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_STREAMS_APPLY_SUM AS SELECT * FROM DBA_HIST_STREAMS_APPLY_SUM WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_STREAMS_CAPTURE AS SELECT * FROM DBA_HIST_STREAMS_CAPTURE WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_STREAMS_POOL_ADVICE AS SELECT * FROM DBA_HIST_STREAMS_POOL_ADVICE WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_SYSMETRIC_HISTORY AS SELECT * FROM DBA_HIST_SYSMETRIC_HISTORY WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_SYSMETRIC_SUMMARY AS SELECT * FROM DBA_HIST_SYSMETRIC_SUMMARY WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_SYSSTAT AS SELECT * FROM DBA_HIST_SYSSTAT WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_SYSTEM_EVENT AS SELECT * FROM DBA_HIST_SYSTEM_EVENT WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_SYS_TIME_MODEL AS SELECT * FROM DBA_HIST_SYS_TIME_MODEL WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_TABLESPACE_STAT AS SELECT * FROM DBA_HIST_TABLESPACE_STAT WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_TBSPC_SPACE_USAGE AS SELECT * FROM DBA_HIST_TBSPC_SPACE_USAGE WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_TEMPFILE AS SELECT * FROM DBA_HIST_TEMPFILE WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_TEMPSTATXS AS SELECT * FROM DBA_HIST_TEMPSTATXS WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_THREAD AS SELECT * FROM DBA_HIST_THREAD WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_TOPLEVELCALL_NAME AS SELECT * FROM DBA_HIST_TOPLEVELCALL_NAME WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_UNDOSTAT AS SELECT * FROM DBA_HIST_UNDOSTAT WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_WAITCLASSMET_HISTORY AS SELECT * FROM DBA_HIST_WAITCLASSMET_HISTORY WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_WAITSTAT AS SELECT * FROM DBA_HIST_WAITSTAT WHERE DBID = &&DBID;
CREATE TABLE &&OWNER..DBA_HIST_WR_CONTROL AS SELECT * FROM DBA_HIST_WR_CONTROL WHERE DBID = &&DBID;

UNDEF OWNER.
UNDEF DBID
